/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AauthedRouteImport } from './routes/aauthed'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppPostsRouteRouteImport } from './routes/_app/posts.route'
import { Route as AppPostsIndexRouteImport } from './routes/_app/posts.index'
import { Route as AppStatisticsUsersRouteImport } from './routes/_app/statistics/users'
import { Route as AppStatisticsSystemRouteImport } from './routes/_app/statistics/system'
import { Route as AppStatisticsSandboxesRouteImport } from './routes/_app/statistics/sandboxes'
import { Route as AppStatisticsPluginsRouteImport } from './routes/_app/statistics/plugins'
import { Route as AppPostsPostIdRouteImport } from './routes/_app/posts.$postId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AauthedRoute = AauthedRouteImport.update({
  id: '/aauthed',
  path: '/aauthed',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPostsRouteRoute = AppPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPostsIndexRoute = AppPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPostsRouteRoute,
} as any)
const AppStatisticsUsersRoute = AppStatisticsUsersRouteImport.update({
  id: '/statistics/users',
  path: '/statistics/users',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStatisticsSystemRoute = AppStatisticsSystemRouteImport.update({
  id: '/statistics/system',
  path: '/statistics/system',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStatisticsSandboxesRoute = AppStatisticsSandboxesRouteImport.update({
  id: '/statistics/sandboxes',
  path: '/statistics/sandboxes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStatisticsPluginsRoute = AppStatisticsPluginsRouteImport.update({
  id: '/statistics/plugins',
  path: '/statistics/plugins',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPostsPostIdRoute = AppPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AppPostsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/aauthed': typeof AauthedRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/posts': typeof AppPostsRouteRouteWithChildren
  '/': typeof AppIndexRoute
  '/posts/$postId': typeof AppPostsPostIdRoute
  '/statistics/plugins': typeof AppStatisticsPluginsRoute
  '/statistics/sandboxes': typeof AppStatisticsSandboxesRoute
  '/statistics/system': typeof AppStatisticsSystemRoute
  '/statistics/users': typeof AppStatisticsUsersRoute
  '/posts/': typeof AppPostsIndexRoute
}
export interface FileRoutesByTo {
  '/aauthed': typeof AauthedRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/': typeof AppIndexRoute
  '/posts/$postId': typeof AppPostsPostIdRoute
  '/statistics/plugins': typeof AppStatisticsPluginsRoute
  '/statistics/sandboxes': typeof AppStatisticsSandboxesRoute
  '/statistics/system': typeof AppStatisticsSystemRoute
  '/statistics/users': typeof AppStatisticsUsersRoute
  '/posts': typeof AppPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/aauthed': typeof AauthedRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/_app/posts': typeof AppPostsRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/posts/$postId': typeof AppPostsPostIdRoute
  '/_app/statistics/plugins': typeof AppStatisticsPluginsRoute
  '/_app/statistics/sandboxes': typeof AppStatisticsSandboxesRoute
  '/_app/statistics/system': typeof AppStatisticsSystemRoute
  '/_app/statistics/users': typeof AppStatisticsUsersRoute
  '/_app/posts/': typeof AppPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/aauthed'
    | '/login'
    | '/logout'
    | '/signup'
    | '/posts'
    | '/'
    | '/posts/$postId'
    | '/statistics/plugins'
    | '/statistics/sandboxes'
    | '/statistics/system'
    | '/statistics/users'
    | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/aauthed'
    | '/login'
    | '/logout'
    | '/signup'
    | '/'
    | '/posts/$postId'
    | '/statistics/plugins'
    | '/statistics/sandboxes'
    | '/statistics/system'
    | '/statistics/users'
    | '/posts'
  id:
    | '__root__'
    | '/_app'
    | '/aauthed'
    | '/login'
    | '/logout'
    | '/signup'
    | '/_app/posts'
    | '/_app/'
    | '/_app/posts/$postId'
    | '/_app/statistics/plugins'
    | '/_app/statistics/sandboxes'
    | '/_app/statistics/system'
    | '/_app/statistics/users'
    | '/_app/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AauthedRoute: typeof AauthedRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aauthed': {
      id: '/aauthed'
      path: '/aauthed'
      fullPath: '/aauthed'
      preLoaderRoute: typeof AauthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/posts': {
      id: '/_app/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AppPostsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/posts/': {
      id: '/_app/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof AppPostsIndexRouteImport
      parentRoute: typeof AppPostsRouteRoute
    }
    '/_app/statistics/users': {
      id: '/_app/statistics/users'
      path: '/statistics/users'
      fullPath: '/statistics/users'
      preLoaderRoute: typeof AppStatisticsUsersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/statistics/system': {
      id: '/_app/statistics/system'
      path: '/statistics/system'
      fullPath: '/statistics/system'
      preLoaderRoute: typeof AppStatisticsSystemRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/statistics/sandboxes': {
      id: '/_app/statistics/sandboxes'
      path: '/statistics/sandboxes'
      fullPath: '/statistics/sandboxes'
      preLoaderRoute: typeof AppStatisticsSandboxesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/statistics/plugins': {
      id: '/_app/statistics/plugins'
      path: '/statistics/plugins'
      fullPath: '/statistics/plugins'
      preLoaderRoute: typeof AppStatisticsPluginsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/posts/$postId': {
      id: '/_app/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AppPostsPostIdRouteImport
      parentRoute: typeof AppPostsRouteRoute
    }
  }
}

interface AppPostsRouteRouteChildren {
  AppPostsPostIdRoute: typeof AppPostsPostIdRoute
  AppPostsIndexRoute: typeof AppPostsIndexRoute
}

const AppPostsRouteRouteChildren: AppPostsRouteRouteChildren = {
  AppPostsPostIdRoute: AppPostsPostIdRoute,
  AppPostsIndexRoute: AppPostsIndexRoute,
}

const AppPostsRouteRouteWithChildren = AppPostsRouteRoute._addFileChildren(
  AppPostsRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppPostsRouteRoute: typeof AppPostsRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppStatisticsPluginsRoute: typeof AppStatisticsPluginsRoute
  AppStatisticsSandboxesRoute: typeof AppStatisticsSandboxesRoute
  AppStatisticsSystemRoute: typeof AppStatisticsSystemRoute
  AppStatisticsUsersRoute: typeof AppStatisticsUsersRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppPostsRouteRoute: AppPostsRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppStatisticsPluginsRoute: AppStatisticsPluginsRoute,
  AppStatisticsSandboxesRoute: AppStatisticsSandboxesRoute,
  AppStatisticsSystemRoute: AppStatisticsSystemRoute,
  AppStatisticsUsersRoute: AppStatisticsUsersRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AauthedRoute: AauthedRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
